# Generated by Django 2.1 on 2019-08-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_wallet', to='users.Wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_wallet', to='users.Wallet')),
            ],
        ),
    ]
